# Generated by Django 3.0.5 on 2020-05-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='BlogContent',
        ),
    ]
