# Generated by Django 3.0.5 on 2020-05-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_auto_20200502_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='post_img',
            field=models.ImageField(default='hello', upload_to='', verbose_name='Thumbnail'),
        ),
    ]
